DROP EVENT IF EXISTS copia_de_clientes;

DELIMITER //

CREATE EVENT copia_de_clientes
ON SCHEDULE EVERY 1 MINUTE
STARTS '2026-02-25 09:46:21'
ENDS   '2026-02-26 09:46:21'
ON COMPLETION NOT PRESERVE
ENABLE
COMMENT 'Copia de clientes'
DO
BEGIN
  DROP TABLE IF EXISTS clientes_copia;
  CREATE TABLE clientes_copia AS
  SELECT * FROM clientes;
END//

DELIMITER ;